version: 2

jobs:
  build:

    branches:
      ignore: gh-pages

    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-npm-deps-{{ checksum "package-lock.json" }}
          - v1-npm-deps-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-npm-deps-{{ checksum "package-lock.json" }}

      - run:
        name: Unit test
        command: npm run test:unit
