version: 2

jobs:
  install:

    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-npm-deps-{{ checksum "package-lock.json" }}
          - v1-npm-deps-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-npm-deps-{{ checksum "package-lock.json" }}

      - persist_to_workspace:
        root: .
        paths:
          - .

  test:

    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - attach_workspace:
        at: .

      - run:
          name: Unit test
          command: npm run test:unit

  deploy:

    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - attach_workspace:
        at: .

      - run:
          name: Deploy
          command: npm run deploy

workflows:
  version: 2
  test_and_deploy:
    - install
    - test
      requires:
        - install
    - deploy
      requires:
        - test
